# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_point_report_check.o

obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_CAF)	+=  focaltech_flash/
